### ISSUE TITLE
Wiat a minute...where is Mohsin\Rest\Classes\ApiManager ?

### ISSUE THREAD

**Issue by adamasantares** [mohsin/oc-auth-plugin#1]
In Plugin.php line 48:
                                                    
  Class "Mohsin\Rest\Classes\ApiManager" not found

**Comment by SaifurRahmanMohsin** [comment]
It's in the [REST plugin](https://github.com/mohsin/oc-rest-plugin/blob/master/classes/ApiManager.php), exactly as mentioned in the first time of the README.
